### ISSUE TITLE
Support PHP 8?

### ISSUE THREAD

**Issue by fd6130** [xputerax/toyyibpay#1]
Hi, how about make this library to support PHP 8?

And also i think we don't need to include `composer.lock` file in a library?

**Comment by xputerax** [comment]
Hi, I will add PHP 8 support ASAP/when I'm free. or you can submit a pull request

I'm not too sure about the composer.lock part though. Did you face any conflict when installing the package due to the lock file?

https://stackoverflow.com/questions/12896780/should-composer-lock-be-committed-to-version-control

**Comment by fd6130** [comment]
Hi, the error occurs most likely because of PHP version in the composer.json. And for the composer.lock, if the composer.lock dependencies are locked in php 7.4 I'm not sure it will cause trouble in project or not (since most library does not commit their composer.lock).


Oh and I will submit a PR sooner.

**Comment by xputerax** [comment]
PHP 8 support added thanks to PR #2
